### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by vihanb** [zyabinVI/SE-Chatbot#6]
Hate to be pissy about this but [you're using](https://github.com/zyabinVI/SE-Chatbot/blob/develop/chatbot.js) my [code](https://github.com/vihanb/SEChatbot). It has no LICENSE so it's considered my intellectual property, meaning you can't use/modify/distribute the code, which is fine if you want to put it into your program or write a quick chatbot in it. But you're:
 - modifying and distributing my code against the copyright (which I don't really care about, ignore this)
 - have your own license

I have a problem with you adding a license to this because you're claiming my code (which you have no rights over), as yours, and granting it access that would of otherwise not been there. I'm not OK with this as would most people, but two easy solutions would be to remove your license so you're not claiming my code as yours or discuss adding license to reference.

**Comment by schas002** [comment]
Okay, so the only thing left is remove the repository. ;_;
